import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    welcome_back: "Welcome Back!",
    dashboard_subtitle: "Here is what's happening in your classes today.",
    total_students: "Total Students",
    total_classes: "Total Classes",
    assignments: "Assignments",
    todays_attendance: "Today's Attendance",
    weekly_attendance: "Weekly Attendance (%)",
    class_average: "Class Average Performance",
    quick_actions: "Quick Actions",
    generate_test: "Generate Test",
    generate_test_sub: "Use AI to create a custom test paper in seconds.",
    create_ppt: "Create Presentation",
    create_ppt_sub: "Upload notes to instantly generate PPT slides.",
    mark_attendance: "Mark Attendance",
    mark_attendance_sub: "Update today's roster for your active classes.",
    overview: "Overview",
    attendance: "Attendance",
    avgScore: "Average Score",
    Mon: "Mon", Tue: "Tue", Wed: "Wed", Thu: "Thu", Fri: "Fri", Sat: "Sat", Sun: "Sun",
    "Week 1": "Week 1", "Week 2": "Week 2", "Week 3": "Week 3", "Week 4": "Week 4",
    test_generator: "Test Generator",
    test_generator_sub: "Configure parameters and let AI draft a bilingual primary school assessment.",
    test_details: "Test Details",
    class_label: "Class",
    subject: "Subject",
    language: "Language",
    marks: "Marks",
    mins: "Mins",
    qty: "Qty",
    syllabus_topics: "Syllabus Topics",
    question_types: "Question Types",
    overall_difficulty: "Overall Difficulty",
    generate_paper: "Generate Test Paper",
    drafting: "Drafting Questions...",
    live_preview: "Live Preview",
    print: "Print",
    download_pdf: "Download PDF",

    // Dropdowns & Difficulties
    "Grade 1": "Grade 1", "Grade 2": "Grade 2", "Grade 3": "Grade 3", "Grade 4": "Grade 4", "Grade 5": "Grade 5",
    "Marathi (First Language)": "Marathi (First Language)",
    "Hindi (Second Language)": "Hindi (Second Language)",
    "English": "English", "Mathematics": "Mathematics", "EVS": "EVS", "EVS - Part 1": "EVS - Part 1", "EVS - Part 2": "EVS - Part 2",
    "Marathi_lang": "Marathi", "English_lang": "English", "Hindi_lang": "Hindi",
    "Easy": "Easy", "Medium": "Medium", "Hard": "Hard",

    "Class 1": "Class 1",
    "Class 2": "Class 2",
    "Class 3": "Class 3",
    "Class 4": "Class 4",
    "Class 5": "Class 5",

    "Marathi": "Marathi",
    "Hindi": "Hindi",
    "EVS Part-1": "EVS - Part 1",
    "EVS Part-2": "EVS - Part 2",
    "EVS - Part 1": "EVS - Part 1",
    "EVS - Part 2": "EVS - Part 2",

    // Question Types
    "MCQs": "MCQs", "True / False": "True / False", "Fill in Blanks": "Fill in Blanks", 
    "Match the Pairs": "Match the Pairs", "One Word Answers": "One Word Answers", 
    "Short Answer": "Short Answer", "Long Answer": "Long Answer",

    // Preview Panel
    "multilingual_gen": "Multilingual Generation",
    "multilingual_gen_sub": "Select your topics and language on the left to generate localized test papers instantly.",
    "curating_questions": "CURATING QUESTIONS...",
    "translating_topics": "Translating topics into the selected language and formatting the paper.",
    "drafting_assessment": "Drafting Assessment",

    // Generated Paper Headers
    "unit_test": "Unit Test",
    "date_label": "Date",
    "max_marks_label": "Max Marks",
    "time_label": "Time",
    "end_of_paper": "*** End of Paper ***",

    // Assignments Page
    "assignment_management": "Assignment Management",
    "assignment_management_sub": "Create, distribute, and track student assignments",
    "create_assignment": "Create Assignment",
    "current_assignments": "Current Assignments",
    "active": "ACTIVE",
    "due": "Due",
    "no_date_set": "No date set",
    "unknown_class": "Unknown Class",
    "edit_assignment": "Edit Assignment",
    "delete_assignment": "Delete Assignment",
    "view_details": "View Details",
    "assignment_description": "Assignment Description",
    "student_grading": "Student Grading",
    "no_students_enrolled": "No students are enrolled in this class yet!",
    "roll": "Roll",
    "graded": "Graded",
    "assign_grade": "Assign Grade",
    "select_grade": "Select Grade...",
    "fail": "Fail",
    "teacher_comments": "Teacher Comments",
    "add_feedback": "Add feedback...",
    "save_new_grades": "Save New Grades",
    "analytics_overview": "Analytics Overview",
    "completion_rate": "Completion Rate",
    "create_new_assignment": "Create New Assignment",
    "assignment_title": "Assignment Title *",
    "class_required": "Class *",
    "description_required": "Description *",
    "due_date": "Due Date *",
    "cancel": "Cancel",
    "save_changes": "Save Changes",
    "no_assignments_found": "No assignments found. Create one to get started!",
    "General": "General",
    
    // 🚀 NEW DROPDOWN PLACEHOLDERS
    select_class: "Select Class",
    select_class_first: "Select Class First",
    select_subject: "Select Subject",

    // Attendance Page
    "attendance_title": "Attendance",
    "attendance_management": "Attendance Management",
    "attendance_management_sub": "Mark, edit, and track daily student attendance",
    "view_history": "View History",
    "submit": "Submit",
    "present": "Present",
    "late": "Late",
    "absent": "Absent",
    "mark_attendance_heading": "Mark Attendance",
    "search_students": "Search students by name or roll...",
    "no_students_found_class": "No students found in this class.",
    "roll_no": "Roll No",
    "select_date": "Select Date",
    "attendance_rate": "Attendance Rate",
    "mark_all_present": "Mark All Present",
    "attendance_history": "Attendance History",
    "last_7_days": "Last 7 Days",
    "no_attendance_records": "No attendance records found for this class.",
    
    // JS Alerts & Days
    "unmarked_warning_1": "You haven't marked",
    "unmarked_warning_2": "students. Submit anyway?",
    "mark_at_least_one": "Please mark attendance for at least one student.",
    "attendance_saved": "Attendance saved successfully!",
    "attendance_failed": "Failed to save attendance.",
    "attendance_error": "An error occurred while submitting.",
    "Su": "Su", "Mo": "Mo", "Tu": "Tu", "We": "We", "Th": "Th", "Fr": "Fr", "Sa": "Sa",

    // PPT Generator Page
    "ppt_generator": "PPT Generator",
    "smart_ppt_maker": "Smart PPT Maker",
    "smart_ppt_maker_sub": "Upload a lesson document and let AI instantly design your presentation slides.",
    "source_document": "Source Document",
    "click_to_change": "Click to change",
    "click_to_upload": "Click to upload document",
    "supports_formats": "Supports .PDF, .TXT, .DOCX, and .PPTX",
    "slide_settings": "Slide Settings",
    "auto_magic": "Auto Magic",
    "manual_topics": "Manual Topics",
    "total_slides_label": "Total Slides (Including Title & Summary)",
    "specific_topics_label": "Specific Topics (One per slide)",
    "topics_placeholder": "e.g. Introduction to Cells\nTypes of Plant Cells\nFunctions of Mitochondria",
    "crafting_presentation": "Crafting Presentation...",
    "generate_pptx": "Generate PPTX",
    "status_panel": "Status Panel",
    "ready_to_design": "Ready to Design",
    "ready_to_design_sub": "Upload your lesson material on the left and click Generate to create a beautifully structured PowerPoint.",
    "analyzing_document": "ANALYZING DOCUMENT...",
    "analyzing_document_sub": "Our advanced AI is reading your file, extracting key points, and formatting beautiful slides.",
    "generating_content": "Generating Content",
    "presentation_ready": "Presentation Ready!",
    "presentation_ready_sub": "Your slide deck has been successfully generated. Click the button below to save it to your computer.",
    "download_presentation": "Download Presentation",
    "generated": "Generated",

    // Errors
    "err_invalid_file": "Please upload a valid .txt, .pdf, .docx, or .pptx file.",
    "err_no_doc": "Please upload a document first.",
    "err_no_topics": "Please enter at least one topic for manual mode.",

    // Students Page
    "student_management": "Student Management",
    "student_directory": "Student Directory",
    "student_directory_sub": "Manage profiles, attendance, and overall performance.",
    "search_student_placeholder": "Search by first name or roll...",
    "all_classes": "All Classes",
    "add_student": "Add Student",
    "no_students_found": "No students found.",
    "unknown": "Unknown",
    "student_profile": "Student Profile",
    "edit_profile": "Edit Profile",
    "call": "Call",
    "personal_details": "Personal Details",
    "roll_number_label": "Roll Number",
    "age_label": "Age",
    "yrs": "yrs",
    "parent_guardian": "Parent / Guardian",
    "parent_email_label": "Parent Email",
    "not_provided": "Not Provided",
    "n_a": "N/A",
    "add_new_student": "Add New Student",
    "edit_student_profile": "Edit Student Profile",
    "first_name_req": "First Name *",
    "last_name_req": "Last Name *",
    "roll_number_req": "Roll Number *",
    "age_opt": "Age",
    "parent_name_req": "Parent Name *",
    "parent_contact_req": "Parent Contact *",
    "parent_email_opt": "Parent Email",
    "update_photo_opt": "Update Photo (Optional)",
    "enroll_student": "Enroll Student",
    "err_saving_student": "Error saving student. Check terminal.",

    // Timetable Page
    "timetable_management": "Timetable Management",
    "timetable_management_sub": "Manage and export your professional weekly schedule",
    "new_subject": "New Subject",
    "export_pdf": "Export PDF",
    "exporting": "Exporting...",
    "time_label": "Time",
    "free_period_short": "Free",
    "generated_on": "Generated on",
    "subject_color_legend": "Subject Color Legend",
    "edit_period": "Edit Period",
    "select_subject_clear": "Select Subject (Or Clear)",
    "room_lab": "Room / Lab",
    "mark_in_progress": "Mark as 'In Progress'",
    "clear": "Clear",
    "add_custom_subject": "Add a custom subject to your roster",
    "subject_name": "Subject Name",
    "color_theme": "Color Theme",
    "select_color": "Select Color",
    "add_subject": "Add Subject",
    "in_progress_badge": "In Progress",

    // Days & Subjects
    "Monday": "Monday", "Tuesday": "Tuesday", "Wednesday": "Wednesday", "Thursday": "Thursday", "Friday": "Friday", "Saturday": "Saturday",
    "Play, Do, Learn": "Play, Do, Learn", "Arts/Work Experience": "Arts/Work Experience",
    "Physical Education": "Physical Education", "Music": "Music", "Computer Science": "Computer Science",
    "Break": "Break", "Lunch Break": "Lunch Break", "Assembly": "Assembly", "Library Period": "Library Period",
    "Study Period": "Study Period", "Free Period": "Free Period", "Parent Meeting": "Parent Meeting", "Half Day": "Half Day",

    "shikshaSahayak": "Shiksha Sahayak",
    "goodMorning": "Good Morning",
    "logout": "Logout",

    // SMART ATTENDANCE (NEW)
    sa_title: "Smart Attendance",
    sa_heading: "AI Vision Attendance",
    sa_beta: "Beta",
    sa_subtitle: "Upload a classroom photo to instantly mark attendance using AI.",
    sa_select_class: "Select Class to Scan",
    sa_choose_class: "-- Choose a Class --",
    sa_upload_title: "Upload Classroom Photo",
    sa_upload_desc: "Make sure the classroom is well-lit and students' faces are visible. Our AI will scan the image and cross-reference it with your student database.",
    sa_browse_files: "Browse Files",
    sa_open_camera: "Open Camera",
    sa_supported_formats: "Supported Formats: JPG, PNG, WEBP",
    sa_analyzing: "ANALYZING FACES",
    sa_cross_referencing: "Cross-referencing student database...",
    sa_scan_complete: "AI Scan Complete",
    sa_detected: "Detected (Present)",
    sa_missing: "Missing (Absent)",
    sa_verify_results: "Verify Results",
    sa_review_findings: "Please review the AI's findings before submitting.",
    sa_no_students: "No students found for this class.",
    sa_roll: "Roll: ",
    sa_match_found: "Match Found",
    sa_mark_present: "Mark Present",
    sa_mark_absent: "Mark Absent",
    sa_rescan: "Rescan",
    sa_confirm_save: "Confirm & Save Attendance",
    sa_alert_select_class: "Please select a class from the dropdown first!",
    sa_alert_mark_all: "Please mark all students as either Present or Absent before saving.",
    sa_alert_success: "✅ AI Attendance successfully saved to database!",
    sa_alert_error: "Error saving attendance: ",
    sa_absent: "Absent",

    // SIDEBAR (NEW)
    sb_dashboard: "Dashboard",
    sb_home: "Home",
    sb_assignments: "Assignments",
    sb_timetable: "Timetable",
    sb_attendance: "Attendance",
    sb_ai_attendance: "AI Attendance",
    sb_ppt_generator: "PPT Generator",
    sb_test_generator: "Test Generator",
    sb_students: "Students",
    sb_leaderboards: "Leaderboards",
    sb_ai_insights: "AI Insights",
    sb_teacher_profile: "Teacher Profile",

    // CHATBOT (NEW)
    cb_welcome: "Hello! I am Shiksha Sahayak. How can I help you teach today?",
    cb_subtitle: "Multilingual Assistant",
    cb_typing: "Sahayak is typing...",
    cb_placeholder: "Ask anything...",
    cb_error: "Sorry, I am having trouble connecting to the server.",
    cb_voice_error: "Sorry, I couldn't process that voice message.",
    cb_browser_error: "Your browser does not support Voice Input. Please use Chrome.",
    cb_mute: "Mute AI Voice",
    cb_unmute: "Replay AI Voice",
    cb_toggle_mic: "Toggle Mic Language",

    // TEACHER PROFILE
    tp_title: "Teacher Profile",
    tp_educator: "Educator",
    tp_no_email: "No email added",
    tp_verified: "Account Verified",
    tp_personal_info: "Personal Information",
    tp_first_name: "First Name",
    tp_last_name: "Last Name",
    tp_email: "Email Address",
    tp_phone: "Phone Number",
    tp_dob: "Date of Birth",
    tp_gender: "Gender",
    tp_select_gender: "Select Gender",
    tp_male: "Male",
    tp_female: "Female",
    tp_other: "Other",
    tp_prefer_not_to_say: "Prefer not to say",
    tp_prof_details: "Professional Details",
    tp_school_name: "School / Institute Name",
    tp_school_ph: "e.g. Pune International School",
    tp_experience: "Teaching Experience",
    tp_select_exp: "Select Experience",
    tp_exp_0_1: "0-1 years",
    tp_exp_1_3: "1-3 years",
    tp_exp_3_5: "3-5 years",
    tp_exp_5_10: "5-10 years",
    tp_exp_10_plus: "10+ years",
    tp_edu_bg: "Educational Background",
    tp_highest_qual: "Highest Qualification",
    tp_select_qual: "Select Qualification",
    tp_qual_ded: "D.El.Ed / D.Ed (Diploma in Education)",
    tp_qual_bed: "B.Ed. / M.Ed. (Education)",
    tp_qual_ba: "B.A. / M.A. (Arts)",
    tp_qual_bsc: "B.Sc. / M.Sc. (Science)",
    tp_qual_bcom: "B.Com. / M.Com. (Commerce)",
    tp_field_study: "Field of Study",
    tp_field_ph: "e.g., Mathematics, English, Child Psychology, etc.",
    tp_bio: "Short Bio / About Me",
    tp_bio_ph: "A brief introduction about your teaching philosophy and background...",
    tp_save_changes: "Save All Changes",
    tp_security: "Security & Password",
    tp_current_pass: "Current Password",
    tp_new_pass: "New Password",
    tp_confirm_pass: "Confirm New Password",
    tp_update_pass: "Update Password"
  },
  mr: {
    welcome_back: "स्वागत आहे!",
    dashboard_subtitle: "आज तुमच्या वर्गात काय घडत आहे ते येथे आहे.",
    total_students: "एकूण विद्यार्थी",
    total_classes: "एकूण वर्ग",
    assignments: "स्वाध्याय",
    todays_attendance: "आजची उपस्थिती",
    weekly_attendance: "साप्ताहिक उपस्थिती (%)",
    class_average: "वर्गाची सरासरी कामगिरी",
    quick_actions: "त्वरित कृती",
    generate_test: "चाचणी तयार करा",
    generate_test_sub: "काही सेकंदात सानुकूल चाचणी पेपर तयार करण्यासाठी AI वापरा.",
    create_ppt: "सादरीकरण तयार करा",
    create_ppt_sub: "पीपीटी स्लाइड्स त्वरित तयार करण्यासाठी नोट्स अपलोड करा.",
    mark_attendance: "उपस्थिती नोंदवा",
    mark_attendance_sub: "तुमच्या सक्रिय वर्गांसाठी आजची उपस्थिती अद्यतनित करा.",
    overview: "आढावा",
    attendance: "उपस्थिती",
    avgScore: "सरासरी गुण",
    Mon: "सोम", Tue: "मंगळ", Wed: "बुध", Thu: "गुरू", Fri: "शुक्र", Sat: "शनी", Sun: "रवी",
    "Week 1": "आठवडा १", "Week 2": "आठवडा २", "Week 3": "आठवडा ३", "Week 4": "आठवडा ४",
    test_generator: "चाचणी जनरेटर",
    test_generator_sub: "पॅरामीटर्स कॉन्फिगर करा आणि AI ला द्विभाषिक प्राथमिक शाळा मूल्यांकन तयार करू द्या.",
    test_details: "चाचणी तपशील",
    class_label: "वर्ग",
    subject: "विषय",
    language: "भाषा",
    marks: "गुण",
    mins: "मिनिटे",
    qty: "संख्या",
    syllabus_topics: "अभ्यासक्रम विषय",
    question_types: "प्रश्नांचे प्रकार",
    overall_difficulty: "एकूण काठिण्य पातळी",
    generate_paper: "चाचणी पेपर तयार करा",
    drafting: "प्रश्न तयार करत आहे...",
    live_preview: "थेट पूर्वावलोकन",
    print: "प्रिंट करा",
    download_pdf: "PDF डाउनलोड करा",
    // Dropdowns & Difficulties
    "Grade 1": "इयत्ता १", "Grade 2": "इयत्ता २", "Grade 3": "इयत्ता ३", "Grade 4": "इयत्ता ४", "Grade 5": "इयत्ता ५",
    "Marathi (First Language)": "मराठी (प्रथम भाषा)",
    "Hindi (Second Language)": "हिंदी (द्वितीय भाषा)",
    "English": "इंग्रजी", "Mathematics": "गणित", "EVS": "परिसर अभ्यास", "EVS - Part 1": "परिसर अभ्यास - भाग १", "EVS - Part 2": "परिसर अभ्यास - भाग २",
    "Marathi_lang": "मराठी", "English_lang": "इंग्रजी", "Hindi_lang": "हिंदी",
    "Easy": "सोपे", "Medium": "मध्यम", "Hard": "कठीण",

    "Class 1": "इयत्ता १",
    "Class 2": "इयत्ता २",
    "Class 3": "इयत्ता ३",
    "Class 4": "इयत्ता ४",
    "Class 5": "इयत्ता ५",

    "Marathi": "मराठी",
    "Hindi": "हिंदी",
    "EVS Part-1": "परिसर अभ्यास - भाग १",
    "EVS Part-2": "परिसर अभ्यास - भाग २",
    "EVS - Part 1": "परिसर अभ्यास - भाग १",
    "EVS - Part 2": "परिसर अभ्यास - भाग २",

    // Question Types
    "MCQs": "बहुपर्यायी प्रश्न (MCQs)", "True / False": "चूक की बरोबर", "Fill in Blanks": "रिकाम्या जागा भरा", 
    "Match the Pairs": "जोड्या जुळवा", "One Word Answers": "एका शब्दात उत्तरे", 
    "Short Answer": "थोडक्यात उत्तरे", "Long Answer": "सविस्तर उत्तरे",

    // Preview Panel
    "multilingual_gen": "बहुभाषिक निर्मिती",
    "multilingual_gen_sub": "त्वरित स्थानिकीकृत चाचणी पेपर तयार करण्यासाठी डावीकडे तुमचे विषय आणि भाषा निवडा.",
    "curating_questions": "प्रश्न तयार करत आहे...",
    "translating_topics": "विषयांचे भाषांतर करत आहे आणि पेपर फॉरमॅट करत आहे.",
    "drafting_assessment": "मूल्यांकन तयार करत आहे",

    // Generated Paper Headers
    "unit_test": "घटक चाचणी",
    "date_label": "दिनांक",
    "max_marks_label": "एकूण गुण",
    "time_label": "वेळ",
    "end_of_paper": "*** पेपर समाप्त ***",

    // Assignments Page
    "assignment_management": "स्वाध्याय व्यवस्थापन",
    "assignment_management_sub": "विद्यार्थ्यांचे स्वाध्याय तयार करा, वितरित करा आणि मागोवा घ्या",
    "create_assignment": "स्वाध्याय तयार करा",
    "current_assignments": "सध्याचे स्वाध्याय",
    "active": "सक्रिय",
    "due": "अंतिम मुदत",
    "no_date_set": "तारीख निश्चित नाही",
    "unknown_class": "अज्ञात वर्ग",
    "edit_assignment": "स्वाध्याय संपादित करा",
    "delete_assignment": "स्वाध्याय हटवा",
    "view_details": "तपशील पहा",
    "assignment_description": "स्वाध्याय वर्णन",
    "student_grading": "विद्यार्थी मूल्यांकन",
    "no_students_enrolled": "या वर्गात अद्याप विद्यार्थी नाहीत!",
    "roll": "हजेरी क्र.",
    "graded": "गुण दिले",
    "assign_grade": "गुण द्या",
    "select_grade": "श्रेणी निवडा...",
    "fail": "नापास",
    "teacher_comments": "शिक्षकांचा अभिप्राय",
    "add_feedback": "अभिप्राय जोडा...",
    "save_new_grades": "नवीन गुण जतन करा",
    "analytics_overview": "विश्लेषण आढावा",
    "completion_rate": "पूर्णता दर",
    "create_new_assignment": "नवीन स्वाध्याय तयार करा",
    "assignment_title": "स्वाध्यायाचे शीर्षक *",
    "class_required": "वर्ग *",
    "description_required": "वर्णन *",
    "due_date": "अंतिम मुदत *",
    "cancel": "रद्द करा",
    "save_changes": "बदल जतन करा",
    "no_assignments_found": "कोणतेही स्वाध्याय आढळले नाहीत. सुरू करण्यासाठी एक तयार करा!",
    "General": "सामान्य",
    
    // 🚀 NEW DROPDOWN PLACEHOLDERS
    select_class: "वर्ग निवडा",
    select_class_first: "प्रथम वर्ग निवडा",
    select_subject: "विषय निवडा",

    // Attendance Page
    "attendance_title": "उपस्थिती",
    "attendance_management": "उपस्थिती व्यवस्थापन",
    "attendance_management_sub": "विद्यार्थ्यांची दैनंदिन उपस्थिती नोंदवा, संपादित करा आणि मागोवा घ्या",
    "view_history": "इतिहास पहा",
    "submit": "जमा करा",
    "present": "हजर",
    "late": "उशिरा",
    "absent": "गैरहजर",
    "mark_attendance_heading": "उपस्थिती नोंदवा",
    "search_students": "नाव किंवा हजेरी क्रमांकानुसार विद्यार्थी शोधा...",
    "no_students_found_class": "या वर्गात कोणतेही विद्यार्थी आढळले नाहीत.",
    "roll_no": "हजेरी क्र.",
    "select_date": "तारीख निवडा",
    "attendance_rate": "उपस्थिती दर",
    "mark_all_present": "सर्वांना हजर नोंदवा",
    "attendance_history": "उपस्थितीचा इतिहास",
    "last_7_days": "मागील ७ दिवस",
    "no_attendance_records": "या वर्गासाठी कोणतीही उपस्थिती नोंद आढळली नाही.",
    
    // JS Alerts & Days
    "unmarked_warning_1": "तुम्ही",
    "unmarked_warning_2": "विद्यार्थ्यांची उपस्थिती नोंदवली नाही. तरीही जमा करायचे?",
    "mark_at_least_one": "कृपया किमान एका विद्यार्थ्याची उपस्थिती नोंदवा.",
    "attendance_saved": "उपस्थिती यशस्वीरित्या जतन केली!",
    "attendance_failed": "उपस्थिती जतन करण्यात अयशस्वी.",
    "attendance_error": "जमा करताना एक त्रुटी आली.",
    "Su": "रवी", "Mo": "सोम", "Tu": "मंगळ", "We": "बुध", "Th": "गुरू", "Fr": "शुक्र", "Sa": "शनी",

    // PPT Generator Page
    "ppt_generator": "PPT जनरेटर",
    "smart_ppt_maker": "स्मार्ट PPT मेकर",
    "smart_ppt_maker_sub": "धड्याचा दस्तऐवज अपलोड करा आणि AI ला झटपट तुमच्या सादरीकरणाच्या स्लाइड्स डिझाइन करू द्या.",
    "source_document": "मूळ दस्तऐवज",
    "click_to_change": "बदलण्यासाठी क्लिक करा",
    "click_to_upload": "दस्तऐवज अपलोड करण्यासाठी क्लिक करा",
    "supports_formats": ".PDF, .TXT, .DOCX, आणि .PPTX ला सपोर्ट करते",
    "slide_settings": "स्लाइड सेटिंग्ज",
    "auto_magic": "ऑटो मॅजिक",
    "manual_topics": "मॅन्युअल विषय",
    "total_slides_label": "एकूण स्लाइड्स (शीर्षक आणि सारांशासह)",
    "specific_topics_label": "विशिष्ट विषय (प्रति स्लाइड एक)",
    "topics_placeholder": "उदा. पेशींची ओळख\nवनस्पती पेशींचे प्रकार\nतंतुकणिकांची कार्ये",
    "crafting_presentation": "सादरीकरण तयार करत आहे...",
    "generate_pptx": "PPTX तयार करा",
    "status_panel": "स्थिती पॅनेल",
    "ready_to_design": "डिझाइन करण्यासाठी तयार",
    "ready_to_design_sub": "डावीकडे तुमची धड्याची सामग्री अपलोड करा आणि सुंदर रचनेचे पॉवरपॉईंट तयार करण्यासाठी 'तयार करा' वर क्लिक करा.",
    "analyzing_document": "दस्तऐवजाचे विश्लेषण करत आहे...",
    "analyzing_document_sub": "आमचे प्रगत AI तुमची फाईल वाचत आहे, मुख्य मुद्दे काढत आहे आणि सुंदर स्लाइड्स फॉरमॅट करत आहे.",
    "generating_content": "सामग्री तयार करत आहे",
    "presentation_ready": "सादरीकरण तयार आहे!",
    "presentation_ready_sub": "तुमचे स्लाइड डेक यशस्वीरित्या तयार झाले आहे. ते तुमच्या संगणकावर सेव्ह करण्यासाठी खालील बटणावर क्लिक करा.",
    "download_presentation": "सादरीकरण डाउनलोड करा",
    "generated": "तयार_केलेले",

    // Errors
    "err_invalid_file": "कृपया वैध .txt, .pdf, .docx, किंवा .pptx फाईल अपलोड करा.",
    "err_no_doc": "कृपया प्रथम एक दस्तऐवज अपलोड करा.",
    "err_no_topics": "कृपया मॅन्युअल मोडसाठी किमान एक विषय प्रविष्ट करा.",

    // Students Page
    "student_management": "विद्यार्थी व्यवस्थापन",
    "student_directory": "विद्यार्थी डिरेक्टरी",
    "student_directory_sub": "प्रोफाईल, उपस्थिती आणि एकूण कामगिरी व्यवस्थापित करा.",
    "search_student_placeholder": "पहिले नाव किंवा हजेरी क्रमांकानुसार शोधा...",
    "all_classes": "सर्व वर्ग",
    "add_student": "विद्यार्थी जोडा",
    "no_students_found": "कोणतेही विद्यार्थी आढळले नाहीत.",
    "unknown": "अज्ञात",
    "student_profile": "विद्यार्थी प्रोफाईल",
    "edit_profile": "प्रोफाईल संपादित करा",
    "call": "कॉल करा",
    "personal_details": "वैयक्तिक तपशील",
    "roll_number_label": "हजेरी क्रमांक",
    "age_label": "वय",
    "yrs": "वर्षे",
    "parent_guardian": "पालक",
    "parent_email_label": "पालकांचा ईमेल",
    "not_provided": "दिलेला नाही",
    "n_a": "माहिती नाही",
    "add_new_student": "नवीन विद्यार्थी जोडा",
    "edit_student_profile": "विद्यार्थ्यांचे प्रोफाईल संपादित करा",
    "first_name_req": "पहिले नाव *",
    "last_name_req": "आडनाव *",
    "roll_number_req": "हजेरी क्रमांक *",
    "age_opt": "वय",
    "parent_name_req": "पालकांचे नाव *",
    "parent_contact_req": "पालकांचा संपर्क *",
    "parent_email_opt": "पालकांचा ईमेल",
    "update_photo_opt": "फोटो अद्यतनित करा (पर्यायी)",
    "enroll_student": "विद्यार्थी नोंदणी करा",
    "err_saving_student": "विद्यार्थी जतन करताना त्रुटी आली.",

    // Timetable Page
    "timetable_management": "वेळापत्रक व्यवस्थापन",
    "timetable_management_sub": "तुमचे व्यावसायिक साप्ताहिक वेळापत्रक व्यवस्थापित करा आणि एक्सपोर्ट करा",
    "new_subject": "नवीन विषय",
    "export_pdf": "PDF एक्सपोर्ट करा",
    "exporting": "एक्सपोर्ट करत आहे...",
    "time_label": "वेळ",
    "free_period_short": "मोकळा तास",
    "generated_on": "या दिवशी तयार केले:",
    "subject_color_legend": "विषय रंग सूची",
    "edit_period": "तास संपादित करा",
    "select_subject_clear": "विषय निवडा (किंवा पुसून टाका)",
    "room_lab": "खोली / प्रयोगशाळा",
    "mark_in_progress": "'सुरू आहे' म्हणून खूण करा",
    "clear": "पुसून टाका",
    "add_custom_subject": "तुमच्या सूचीमध्ये एक सानुकूल विषय जोडा",
    "subject_name": "विषयाचे नाव",
    "color_theme": "रंग (थीम)",
    "select_color": "रंग निवडा",
    "add_subject": "विषय जोडा",
    "in_progress_badge": "सुरू आहे",

    // Days & Subjects
    "Monday": "सोमवार", "Tuesday": "मंगळवार", "Wednesday": "बुधवार", "Thursday": "गुरुवार", "Friday": "शुक्रवार", "Saturday": "शनिवार",
    "Play, Do, Learn": "खेळू, करू, शिकू", "Arts/Work Experience": "कला/कार्यानुभव",
    "Physical Education": "शारीरिक शिक्षण", "Music": "संगीत", "Computer Science": "संगणक विज्ञान",
    "Break": "लहान सुट्टी", "Lunch Break": "मधली सुट्टी", "Assembly": "परिपाठ", "Library Period": "ग्रंथालय तास",
    "Study Period": "अभ्यास तास", "Free Period": "मोकळा तास", "Parent Meeting": "पालक सभा", "Half Day": "अर्धा दिवस",

    "shikshaSahayak": "शिक्षा सहाय्यक",
    "goodMorning": "शुभ प्रभात",
    "logout": "लॉग आउट",

    // SMART ATTENDANCE (NEW)
    sa_title: "स्मार्ट उपस्थिती",
    sa_heading: "एआय व्हिजन उपस्थिती",
    sa_beta: "बीटा",
    sa_subtitle: "एआय चा वापर करून त्वरित उपस्थिती नोंदवण्यासाठी वर्गाचा फोटो अपलोड करा.",
    sa_select_class: "स्कॅन करण्यासाठी वर्ग निवडा",
    sa_choose_class: "-- एक वर्ग निवडा --",
    sa_upload_title: "वर्गाचा फोटो अपलोड करा",
    sa_upload_desc: "वर्गात चांगला प्रकाश असल्याची आणि विद्यार्थ्यांचे चेहरे दिसत असल्याची खात्री करा. आमचा एआय फोटो स्कॅन करेल आणि तुमच्या विद्यार्थी डेटाबेसशी त्याची पडताळणी करेल.",
    sa_browse_files: "फाईल्स ब्राउझ करा",
    sa_open_camera: "कॅमेरा उघडा",
    sa_supported_formats: "समर्थित फॉरमॅट्स: JPG, PNG, WEBP",
    sa_analyzing: "चेहऱ्यांचे विश्लेषण करत आहे",
    sa_cross_referencing: "विद्यार्थी डेटाबेसशी पडताळणी करत आहे...",
    sa_scan_complete: "एआय स्कॅन पूर्ण झाले",
    sa_detected: "आढळले (उपस्थित)",
    sa_missing: "गैरहजर (अनुपस्थित)",
    sa_verify_results: "निकाल तपासा",
    sa_review_findings: "सबमिट करण्यापूर्वी कृपया एआय चे निष्कर्ष तपासा.",
    sa_no_students: "या वर्गासाठी कोणतेही विद्यार्थी आढळले नाहीत.",
    sa_roll: "रोल: ",
    sa_match_found: "जुळले",
    sa_mark_present: "उपस्थित नोंदवा",
    sa_mark_absent: "गैरहजर नोंदवा",
    sa_rescan: "पुन्हा स्कॅन करा",
    sa_confirm_save: "निश्चित करा आणि उपस्थिती सेव्ह करा",
    sa_alert_select_class: "कृपया आधी ड्रॉपडाउनमधून वर्ग निवडा!",
    sa_alert_mark_all: "कृपया सेव्ह करण्यापूर्वी सर्व विद्यार्थ्यांना उपस्थित किंवा गैरहजर म्हणून नोंदवा.",
    sa_alert_success: "✅ एआय उपस्थिती यशस्वीरित्या डेटाबेसमध्ये सेव्ह केली!",
    sa_alert_error: "उपस्थिती सेव्ह करताना त्रुटी: ",

    // SIDEBAR (NEW)
    sb_dashboard: "डॅशबोर्ड",
    sb_home: "मुख्यपृष्ठ",
    sb_assignments: "स्वाध्याय",
    sb_timetable: "वेळापत्रक",
    sb_attendance: "उपस्थिती",
    sb_ai_attendance: "एआय उपस्थिती",
    sb_ppt_generator: "PPT जनरेटर",
    sb_test_generator: "चाचणी जनरेटर",
    sb_students: "विद्यार्थी",
    sb_leaderboards: "लीडरबोर्ड",
    sb_ai_insights: "एआय विश्लेषण",
    sb_teacher_profile: "शिक्षक प्रोफाईल",

    // CHATBOT (NEW)
    cb_welcome: "नमस्कार! मी शिक्षा सहायक आहे. आज तुम्हाला शिकवण्यात मी कशी मदत करू?",
    cb_subtitle: "बहुभाषिक सहाय्यक",
    cb_typing: "सहायक लिहीत आहे...",
    cb_placeholder: "काहीही विचारा...",
    cb_error: "क्षमस्व, सर्व्हरशी कनेक्ट करण्यात अडचण येत आहे.",
    cb_voice_error: "क्षमस्व, मी तो व्हॉइस संदेश प्रक्रिया करू शकलो नाही.",
    cb_browser_error: "तुमचा ब्राउझर व्हॉइस इनपुटला सपोर्ट करत नाही. कृपया क्रोम वापरा.",
    cb_mute: "एआई आवाज बंद करा",
    cb_unmute: "एआई आवाज पुन्हा सुरू करा",
    cb_toggle_mic: "माईकची भाषा बदला",

    // TEACHER PROFILE
    tp_title: "शिक्षक प्रोफाईल",
    tp_educator: "शिक्षक",
    tp_no_email: "ईमेल जोडलेला नाही",
    tp_verified: "खाते सत्यापित",
    tp_personal_info: "वैयक्तिक माहिती",
    tp_first_name: "पहिले नाव",
    tp_last_name: "आडनाव",
    tp_email: "ईमेल पत्ता",
    tp_phone: "फोन नंबर",
    tp_dob: "जन्म तारीख",
    tp_gender: "लिंग",
    tp_select_gender: "लिंग निवडा",
    tp_male: "पुरुष",
    tp_female: "स्त्री",
    tp_other: "इतर",
    tp_prefer_not_to_say: "सांगू इच्छित नाही",
    tp_prof_details: "व्यावसायिक तपशील",
    tp_school_name: "शाळा / संस्थेचे नाव",
    tp_school_ph: "उदा. पुणे इंटरनॅशनल स्कूल",
    tp_experience: "शिकवण्याचा अनुभव",
    tp_select_exp: "अनुभव निवडा",
    tp_exp_0_1: "०-१ वर्षे",
    tp_exp_1_3: "१-३ वर्षे",
    tp_exp_3_5: "३-५ वर्षे",
    tp_exp_5_10: "५-१० वर्षे",
    tp_exp_10_plus: "१०+ वर्षे",
    tp_edu_bg: "शैक्षणिक पार्श्वभूमी",
    tp_highest_qual: "सर्वोच्च शिक्षण",
    tp_select_qual: "शिक्षण निवडा",
    tp_qual_ded: "डी.एल.एड / डी.एड (शिक्षण पदविका)",
    tp_qual_bed: "बी.एड. / एम.एड. (शिक्षणशास्त्र)",
    tp_qual_ba: "बी.ए. / एम.ए. (कला)",
    tp_qual_bsc: "बी.एस्सी. / एम.एस्सी. (विज्ञान)",
    tp_qual_bcom: "बी.कॉम. / एम.कॉम. (वाणिज्य)",
    tp_field_study: "शिक्षणाचे क्षेत्र",
    tp_field_ph: "उदा. गणित, इंग्रजी, बालमानसशास्त्र, इ.",
    tp_bio: "थोडक्यात परिचय / माझ्याबद्दल",
    tp_bio_ph: "तुमचे शिक्षण तत्त्वज्ञान आणि पार्श्वभूमीबद्दल थोडक्यात माहिती...",
    tp_save_changes: "सर्व बदल जतन करा",
    tp_security: "सुरक्षा आणि पासवर्ड",
    tp_current_pass: "सध्याचा पासवर्ड",
    tp_new_pass: "नवीन पासवर्ड",
    tp_confirm_pass: "नवीन पासवर्डची पुष्टी करा",
    tp_update_pass: "पासवर्ड अपडेट करा"
  },
  hi: {
    welcome_back: "वापसी पर स्वागत है!",
    dashboard_subtitle: "आज आपकी कक्षाओं में यह हो रहा है。",
    total_students: "कुल छात्र",
    total_classes: "कुल कक्षाएं",
    assignments: "असाइनमेंट",
    todays_attendance: "आज की उपस्थिति",
    weekly_attendance: "साप्ताहिक उपस्थिति (%)",
    class_average: "कक्षा का औसत प्रदर्शन",
    quick_actions: "त्वरित कार्रवाई",
    generate_test: "टेस्ट बनाएं",
    generate_test_sub: "एआई का उपयोग करके सेकंडों में कस्टम टेस्ट पेपर बनाएं।",
    create_ppt: "प्रस्तुति बनाएं",
    create_ppt_sub: "पीपीटी स्लाइड तुरंत बनाने के लिए नोट्स अपलोड करें।",
    mark_attendance: "उपस्थिति दर्ज करें",
    mark_attendance_sub: "अपनी सक्रिय कक्षाओं के लिए आज का रोस्टर अपडेट करें।",
    overview: "अवलोकन",
    attendance: "उपस्थिति",
    avgScore: "औसत अंक",
    Mon: "सोम", Tue: "मंगल", Wed: "बुध", Thu: "गुरु", Fri: "शुक्र", Sat: "शनि", Sun: "रवि",
    "Week 1": "सप्ताह 1", "Week 2": "सप्ताह 2", "Week 3": "सप्ताह 3", "Week 4": "सप्ताह 4",
    test_generator: "टेस्ट जेनरेटर",
    test_generator_sub: "पैरामीटर सेट करें और एआई को प्राथमिक स्कूल का पेपर बनाने दें।",
    test_details: "टेस्ट विवरण",
    class_label: "कक्षा",
    subject: "विषय",
    language: "भाषा",
    marks: "अंक",
    mins: "मिनट",
    qty: "मात्रा",
    syllabus_topics: "पाठ्यक्रम के विषय",
    question_types: "प्रश्नों के प्रकार",
    overall_difficulty: "कठिनाई स्तर",
    generate_paper: "टेस्ट पेपर बनाएं",
    drafting: "प्रश्न तैयार किए जा रहे हैं...",
    live_preview: "लाइव पूर्वावलोकन",
    print: "प्रिंट करें",
    download_pdf: "पीडीएफ डाउनलोड करें",

    // Dropdowns & Difficulties
    "Grade 1": "कक्षा 1", "Grade 2": "कक्षा 2", "Grade 3": "कक्षा 3", "Grade 4": "कक्षा 4", "Grade 5": "कक्षा 5",
    "Marathi (First Language)": "मराठी (प्रथम भाषा)",
    "Hindi (Second Language)": "हिंदी (द्वितीय भाषा)",
    "English": "अंग्रेज़ी", "Mathematics": "गणित", "EVS": "पर्यावरण अध्ययन", "EVS - Part 1": "पर्यावरण अध्ययन - भाग 1", "EVS - Part 2": "पर्यावरण अध्ययन - भाग 2",
    "Marathi_lang": "मराठी", "English_lang": "अंग्रेज़ी", "Hindi_lang": "हिंदी",
    "Easy": "आसान", "Medium": "मध्यम", "Hard": "कठिन",
    
    // Question Types
    "MCQs": "बहुविकल्पीय प्रश्न (MCQs)", "True / False": "सही / गलत", "Fill in Blanks": "रिक्त स्थान भरें", 
    "Match the Pairs": "जोड़े मिलाएं", "One Word Answers": "एक शब्द में उत्तर", 
    "Short Answer": "लघु उत्तर", "Long Answer": "दीर्घ उत्तर",

    // Preview Panel
    "multilingual_gen": "बहुभाषी निर्माण",
    "multilingual_gen_sub": "तुरंत स्थानीयकृत टेस्ट पेपर बनाने के लिए अपने विषय और भाषा का चयन करें।",
    "curating_questions": "प्रश्न तैयार किए जा रहे हैं...",
    "translating_topics": "विषयों का अनुवाद किया जा रहा है और पेपर को स्वरूपित किया जा रहा है।",
    "drafting_assessment": "मूल्यांकन का प्रारूप तैयार किया जा रहा है",

    // Generated Paper Headers
    "unit_test": "यूनिट टेस्ट",
    "date_label": "दिनांक",
    "max_marks_label": "अधिकतम अंक",
    "time_label": "समय",
    "end_of_paper": "*** पेपर समाप्त ***",

    // Assignments Page
    "assignment_management": "असाइनमेंट प्रबंधन",
    "assignment_management_sub": "छात्रों के असाइनमेंट बनाएं, वितरित करें और ट्रैक करें",
    "create_assignment": "असाइनमेंट बनाएं",
    "current_assignments": "वर्तमान असाइनमेंट",
    "active": "सक्रिय",
    "due": "अंतिम तिथि",
    "no_date_set": "तारीख तय नहीं",
    "unknown_class": "अज्ञात कक्षा",
    "edit_assignment": "असाइनमेंट संपादित करें",
    "delete_assignment": "असाइनमेंट हटाएं",
    "view_details": "विवरण देखें",
    "assignment_description": "असाइनमेंट विवरण",
    "student_grading": "छात्र ग्रेडिंग",
    "no_students_enrolled": "इस कक्षा में अभी तक कोई छात्र नहीं है!",
    "roll": "रोल नं.",
    "graded": "ग्रेड दिया गया",
    "assign_grade": "ग्रेड दें",
    "select_grade": "ग्रेड चुनें...",
    "fail": "फेल",
    "teacher_comments": "शिक्षक की टिप्पणी",
    "add_feedback": "फीडबैक जोड़ें...",
    "save_new_grades": "नए ग्रेड सहेजें",
    "analytics_overview": "एनालिटिक्स अवलोकन",
    "completion_rate": "पूर्णता दर",
    "create_new_assignment": "नया असाइनमेंट बनाएं",
    "assignment_title": "असाइनमेंट शीर्षक *",
    "class_required": "कक्षा *",
    "description_required": "विवरण *",
    "due_date": "अंतिम तिथि *",
    "cancel": "रद्द करें",
    "save_changes": "बदलाव सहेजें",
    "no_assignments_found": "कोई असाइनमेंट नहीं मिला। शुरू करने के लिए एक बनाएं!",
    "General": "सामान्य",
    
    // 🚀 NEW DROPDOWN PLACEHOLDERS
    select_class: "कक्षा चुनें",
    select_class_first: "पहले कक्षा चुनें",
    select_subject: "विषय चुनें",

    // Attendance Page
    "attendance_title": "उपस्थिति",
    "attendance_management": "उपस्थिति प्रबंधन",
    "attendance_management_sub": "छात्रों की दैनिक उपस्थिति दर्ज करें, संपादित करें और ट्रैक करें",
    "view_history": "इतिहास देखें",
    "submit": "जमा करें",
    "present": "उपस्थित",
    "late": "देर से",
    "absent": "अनुपस्थित",
    "mark_attendance_heading": "उपस्थिति दर्ज करें",
    "search_students": "नाम या रोल नंबर से छात्र खोजें...",
    "no_students_found_class": "इस कक्षा में कोई छात्र नहीं मिला।",
    "roll_no": "रोल नं.",
    "select_date": "तारीख चुनें",
    "attendance_rate": "उपस्थिति दर",
    "mark_all_present": "सभी को उपस्थित दर्ज करें",
    "attendance_history": "उपस्थिति का इतिहास",
    "last_7_days": "पिछले 7 दिन",
    "no_attendance_records": "इस कक्षा के लिए उपस्थिति का कोई रिकॉर्ड नहीं मिला।",
    
    // JS Alerts & Days
    "unmarked_warning_1": "आपने",
    "unmarked_warning_2": "छात्रों की उपस्थिति दर्ज नहीं की है। क्या फिर भी जमा करना है?",
    "mark_at_least_one": "कृपया कम से कम एक छात्र की उपस्थिति दर्ज करें।",
    "attendance_saved": "उपस्थिति सफलतापूर्वक सहेजी गई!",
    "attendance_failed": "उपस्थिति सहेजने में विफल।",
    "attendance_error": "जमा करते समय एक त्रुटि हुई।",
    "Su": "रवि", "Mo": "सोम", "Tu": "मंगल", "We": "बुध", "Th": "गुरु", "Fr": "शुक्र", "Sa": "शनि",

    // PPT Generator Page
    "ppt_generator": "पीपीटी जेनरेटर",
    "smart_ppt_maker": "स्मार्ट पीपीटी मेकर",
    "smart_ppt_maker_sub": "पाठ दस्तावेज़ अपलोड करें और एआई को तुरंत आपकी प्रस्तुति डिज़ाइन करने दें।",
    "source_document": "स्रोत दस्तावेज़",
    "click_to_change": "बदलने के लिए क्लिक करें",
    "click_to_upload": "दस्तावेज़ अपलोड करने के लिए क्लिक करें",
    "supports_formats": "समर्थित प्रारूप: .PDF, .TXT, .DOCX, और .PPTX",
    "slide_settings": "स्लाइड सेटिंग्स",
    "auto_magic": "ऑटो मैजिक",
    "manual_topics": "मैन्युअल विषय",
    "total_slides_label": "कुल स्लाइड (शीर्षक और सारांश सहित)",
    "specific_topics_label": "विशिष्ट विषय (प्रति स्लाइड एक)",
    "topics_placeholder": "उदा. कोशिकाओं का परिचय\nपौधों की कोशिकाओं के प्रकार\nमाइटोकॉन्ड्रिया के कार्य",
    "crafting_presentation": "प्रस्तुति तैयार की जा रही है...",
    "generate_pptx": "पीपीटीएक्स बनाएं",
    "status_panel": "स्थिति पैनल",
    "ready_to_design": "डिज़ाइन के लिए तैयार",
    "ready_to_design_sub": "बाईं ओर अपनी पाठ्य सामग्री अपलोड करें और एक शानदार प्रस्तुति बनाने के लिए 'जेनरेट' पर क्लिक करें।",
    "analyzing_document": "दस्तावेज़ का विश्लेषण किया जा रहा है...",
    "analyzing_document_sub": "हमारा एआई आपकी फ़ाइल पढ़ रहा है, मुख्य बिंदु निकाल रहा है और स्लाइड स्वरूपित कर रहा है।",
    "generating_content": "सामग्री तैयार की जा रही है",
    "presentation_ready": "प्रस्तुति तैयार है!",
    "presentation_ready_sub": "आपकी स्लाइड सफलतापूर्वक जनरेट हो गई है। इसे कंप्यूटर पर सहेजने के लिए नीचे दिए गए बटन पर क्लिक करें।",
    "download_presentation": "प्रस्तुति डाउनलोड करें",
    "generated": "जेनरेट किया गया",

    // Errors
    "err_invalid_file": "कृपया एक मान्य .txt, .pdf, .docx, या .pptx फ़ाइल अपलोड करें।",
    "err_no_doc": "कृपया पहले एक दस्तावेज़ अपलोड करें।",
    "err_no_topics": "कृपया मैन्युअल मोड के लिए कम से कम एक विषय दर्ज करें।",

    // Students Page
    "student_management": "छात्र प्रबंधन",
    "student_directory": "छात्र निर्देशिका",
    "student_directory_sub": "प्रोफ़ाइल, उपस्थिति और समग्र प्रदर्शन का प्रबंधन करें।",
    "search_student_placeholder": "प्रथम नाम या रोल नंबर से खोजें...",
    "all_classes": "सभी कक्षाएं",
    "add_student": "छात्र जोड़ें",
    "no_students_found": "कोई छात्र नहीं मिला।",
    "unknown": "अज्ञात",
    "student_profile": "छात्र प्रोफ़ाइल",
    "edit_profile": "प्रोफ़ाइल संपादित करें",
    "call": "कॉल करें",
    "personal_details": "व्यक्तिगत विवरण",
    "roll_number_label": "रोल नंबर",
    "age_label": "आयु",
    "yrs": "वर्ष",
    "parent_guardian": "माता-पिता / अभिभावक",
    "parent_email_label": "माता-पिता का ईमेल",
    "not_provided": "प्रदान नहीं किया गया",
    "n_a": "उपलब्ध नहीं",
    "add_new_student": "नया छात्र जोड़ें",
    "edit_student_profile": "छात्र प्रोफ़ाइल संपादित करें",
    "first_name_req": "प्रथम नाम *",
    "last_name_req": "अंतिम नाम *",
    "roll_number_req": "रोल नंबर *",
    "age_opt": "आयु",
    "parent_name_req": "माता-पिता का नाम *",
    "parent_contact_req": "संपर्क नंबर *",
    "parent_email_opt": "ईमेल (वैकल्पिक)",
    "update_photo_opt": "फोटो अपडेट करें (वैकल्पिक)",
    "enroll_student": "छात्र को नामांकित करें",
    "err_saving_student": "छात्र को सहेजने में त्रुटि।",

    // Timetable Page
    "timetable_management": "समय सारिणी प्रबंधन",
    "timetable_management_sub": "अपना साप्ताहिक शेड्यूल प्रबंधित और निर्यात करें",
    "new_subject": "नया विषय",
    "export_pdf": "पीडीएफ निर्यात करें",
    "exporting": "निर्यात हो रहा है...",
    "time_label": "समय",
    "free_period_short": "खाली",
    "generated_on": "जेनरेट किया गया:",
    "subject_color_legend": "विषय रंग सूची",
    "edit_period": "अवधि संपादित करें",
    "select_subject_clear": "विषय चुनें (या साफ़ करें)",
    "room_lab": "कमरा / लैब",
    "mark_in_progress": "'प्रगति पर' के रूप में चिह्नित करें",
    "clear": "साफ़ करें",
    "add_custom_subject": "अपनी सूची में एक कस्टम विषय जोड़ें",
    "subject_name": "विषय का नाम",
    "color_theme": "रंग थीम",
    "select_color": "रंग चुनें",
    "add_subject": "विषय जोड़ें",
    "in_progress_badge": "प्रगति पर",

    // Days & Subjects
    "Monday": "सोमवार", "Tuesday": "मंगलवार", "Wednesday": "बुधवार", "Thursday": "गुरुवार", "Friday": "शुक्रवार", "Saturday": "शनिवार",
    "Play, Do, Learn": "खेलें, करें, सीखें", "Arts/Work Experience": "कला/कार्य अनुभव",
    "Physical Education": "शारीरिक शिक्षा", "Music": "संगीत", "Computer Science": "कंप्यूटर विज्ञान",
    "Break": "ब्रेक", "Lunch ब्रेक": "लंच ब्रेक", "Assembly": "प्रार्थना सभा", "Library Period": "पुस्तकालय",
    "Study Period": "अध्ययन", "Free Period": "खाली समय", "Parent Meeting": "पीटीएम (PTM)", "Half Day": "आधा दिन",

    "shikshaSahayak": "शिक्षा सहायक",
    "goodMorning": "सुप्रभात",
    "logout": "लॉग आउट",

    // SMART ATTENDANCE (NEW)
    sa_title: "स्मार्ट उपस्थिति",
    sa_heading: "एआय विज़न उपस्थिति",
    sa_beta: "बीटा",
    sa_subtitle: "एआई का उपयोग करके तुरंत उपस्थिति दर्ज करने के लिए कक्षा की तस्वीर अपलोड करें।",
    sa_select_class: "स्कैन करने के लिए कक्षा चुनें",
    sa_choose_class: "-- एक कक्षा चुनें --",
    sa_upload_title: "कक्षा की तस्वीर अपलोड करें",
    sa_upload_desc: "सुनिश्चित करें कि कक्षा में अच्छी रोशनी हो और छात्रों के चेहरे दिखाई दें। हमारा एआई छवि को स्कैन करेगा और आपके छात्र डेटाबेस के साथ इसका मिलान करेगा।",
    sa_browse_files: "फ़ाइलें ब्राउज़ करें",
    sa_open_camera: "कैमरा खोलें",
    sa_supported_formats: "समर्थित प्रारूप: JPG, PNG, WEBP",
    sa_analyzing: "चेहरों का विश्लेषण हो रहा है",
    sa_cross_referencing: "छात्र डेटाबेस से मिलान किया जा रहा है...",
    sa_scan_complete: "एआई स्कैन पूरा हुआ",
    sa_detected: "पाए गए (उपस्थित)",
    sa_missing: "गायब (अनुपस्थित)",
    sa_verify_results: "परिणाम सत्यापित करें",
    sa_review_findings: "सबमिट करने से पहले कृपया एआई के निष्कर्षों की समीक्षा करें।",
    sa_no_students: "इस कक्षा के लिए कोई छात्र नहीं मिला।",
    sa_roll: "रोल: ",
    sa_match_found: "मिलान पाया गया",
    sa_mark_present: "उपस्थित दर्ज करें",
    sa_mark_absent: "अनुपस्थित दर्ज करें",
    sa_rescan: "फिर से स्कैन करें",
    sa_confirm_save: "पुष्टि करें और उपस्थिति सहेजें",
    sa_alert_select_class: "कृपया पहले ड्रॉपडाउन से एक कक्षा चुनें!",
    sa_alert_mark_all: "कृपया सहेजने से पहले सभी छात्रों को उपस्थित या अनुपस्थित के रूप में चिह्नित करें।",
    sa_alert_success: "✅ एआई उपस्थिति सफलतापूर्वक डेटाबेस में सहेजी गई!",
    sa_alert_error: "उपस्थिती सहेजने में त्रुटि: ",

    // SIDEBAR (NEW)
    sb_dashboard: "डैशबोर्ड",
    sb_home: "मुख्य पृष्ठ",
    sb_assignments: "असाइनमेंट",
    sb_timetable: "समय सारिणी",
    sb_attendance: "उपस्थिति",
    sb_ai_attendance: "एआई उपस्थिति",
    sb_ppt_generator: "पीपीटी जेनरेटर",
    sb_test_generator: "टेस्ट जेनरेटर",
    sb_students: "छात्र",
    sb_leaderboards: "लीडरबोर्ड",
    sb_ai_insights: "एआई अंतर्दृष्टि",
    sb_teacher_profile: "शिक्षक प्रोफ़ाइल",

    // CHATBOT (NEW)
    cb_welcome: "नमस्ते! मैं शिक्षा सहायक हूँ। आज आपको पढ़ाने में मैं कैसे सहायता कर सकता हूँ?",
    cb_subtitle: "बहुभाषी सहायक",
    cb_typing: "सहायक लिख रहा है...",
    cb_placeholder: "कुछ भी पूछें...",
    cb_error: "क्षमा करें, सर्वर से जुड़ने में समस्या हो रही है।",
    cb_voice_error: "क्षमा करें, मैं इस वॉइस मैसेज को प्रोसेस नहीं कर सका।",
    cb_browser_error: "आपका ब्राउज़र वॉइस इनपुट का समर्थन नहीं करता है। कृपया क्रोम का उपयोग करें।",
    cb_mute: "एआई आवाज़ बंद करें",
    cb_unmute: "एआई आवाज़ पुनः चालू करें",
    cb_toggle_mic: "माइक की भाषा बदलें",

    // TEACHER PROFILE
    tp_title: "शिक्षक प्रोफ़ाइल",
    tp_educator: "शिक्षक",
    tp_no_email: "ईमेल नहीं जोड़ा गया",
    tp_verified: "खाता सत्यापित",
    tp_personal_info: "व्यक्तिगत जानकारी",
    tp_first_name: "प्रथम नाम",
    tp_last_name: "अंतिम नाम",
    tp_email: "ईमेल पता",
    tp_phone: "फ़ोन नंबर",
    tp_dob: "जन्म तिथि",
    tp_gender: "लिंग",
    tp_select_gender: "लिंग चुनें",
    tp_male: "पुरुष",
    tp_female: "महिला",
    tp_other: "अन्य",
    tp_prefer_not_to_say: "बताना नहीं चाहते",
    tp_prof_details: "पेशेवर विवरण",
    tp_school_name: "स्कूल / संस्थान का नाम",
    tp_school_ph: "उदा. पुणे इंटरनेशनल स्कूल",
    tp_experience: "शिक्षण अनुभव",
    tp_select_exp: "अनुभव चुनें",
    tp_exp_0_1: "0-1 वर्ष",
    tp_exp_1_3: "1-3 वर्ष",
    tp_exp_3_5: "3-5 वर्ष",
    tp_exp_5_10: "5-10 वर्ष",
    tp_exp_10_plus: "10+ वर्ष",
    tp_edu_bg: "शैक्षिक पृष्ठभूमि",
    tp_highest_qual: "उच्चतम योग्यता",
    tp_select_qual: "योग्यता चुनें",
    tp_qual_ded: "डी.एल.एड / डी.एड (शिक्षा में डिप्लोमा)",
    tp_qual_bed: "बी.एड. / एम.एड. (शिक्षा)",
    tp_qual_ba: "बी.ए. / एम.ए. (कला)",
    tp_qual_bsc: "बी.एससी. / एम.एससी. (विज्ञान)",
    tp_qual_bcom: "बी.कॉम. / एम.कॉम. (वाणिज्य)",
    tp_field_study: "अध्ययन का क्षेत्र",
    tp_field_ph: "उदा. गणित, अंग्रेजी, बाल मनोविज्ञान, आदि।",
    tp_bio: "संक्षिप्त परिचय / मेरे बारे में",
    tp_bio_ph: "आपके शिक्षण दर्शन और पृष्ठभूमि के बारे में एक संक्षिप्त परिचय...",
    tp_save_changes: "सभी परिवर्तन सहेजें",
    tp_security: "सुरक्षा और पासवर्ड",
    tp_current_pass: "वर्तमान पासवर्ड",
    tp_new_pass: "नया पासवर्ड",
    tp_confirm_pass: "नए पासवर्ड की पुष्टि करें",
    tp_update_pass: "पासवर्ड अपडेट करें"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // Default to English
  const [language, setLanguage] = useState('en');

  // The magical 't' function that translates text
  const t = (key) => {
    return translations[language][key] || key; // Falls back to the key if translation is missing
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);