"""Added profile columns to Teacher

Revision ID: 33bf5c8c8def
Revises: 
Create Date: 2026-05-25 15:53:39.417569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bf5c8c8def'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field_of_study', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('field_of_study')
        batch_op.drop_column('qualification')
        batch_op.drop_column('gender')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
